// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(version_num))]
pub struct AlembicVersion {
    pub version_num: String,
}

#[derive(Queryable, Debug)]
pub struct FibEntry {
    pub id: i32,
    pub input_number: Option<i32>,
    pub calculated_number: Option<i32>,
}

